---
- name: Install Apache
  apt:
    name: apache2
    state: latest

- name: Start the Service
  service:
    name: apache2
    state: started
    enabled: true

- name: Deleting Existing Index File
  file:
    state: absent
    path: /var/www/html/index.html

- name: Copy Index File
  copy:
    src: ./index.php
    dest: /var/www/html/
  notify: restart apache2

- name: Install PHP
  apt:
    name: php
    state: latest

- name: Install Apache PHP Modules
  apt:
    name: libapache2-mod-php
    state: latest

- name: Running task 02
  connection: local
  script: /root/ansible/task2.sh  
